version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pipenv install -e .
      - run:
          command: |
            pipenv shell
            rc